[project]
name = "membase"
version = "0.1.6"
description = "python sdk for membase operation: memory, knowledge, chain, auth etc."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=0.6.3",
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "web3>=7.8.0",
]
