[project]
name = "membase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=0.6.3",
    "loguru>=0.7.3",
    "requests>=2.32.3",
]
